name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 
      - uses: actions/checkout@v2

      # Vamos a establecer un environment de python 3.6
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
        
                
      # Instalamos la dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Corremos nuestros testsss
      - name: Run unit tests
        run: |
          pytest

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "146.59.155.170"
          username: ${{ secrets.HOSTNAME }}
          password: ${{ secrets.HOSTPASS }}
          port: 22
          source: "./docker-compose.yml, ./docker-entrypoint.sh"
          target: "."
          
      - name: Docker Compose Actions Workflow       
        uses: actions/checkout@v2
            
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "146.59.155.170"
          username: ${{ secrets.HOSTNAME }}
          password: ${{ secrets.HOSTPASS }}
          port: 22
          script: docker-compose -d up    
