name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 
      - uses: actions/checkout@v2

      # Vamos a establecer un environment de python 3.6
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
        
                
      # Instalamos la dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Corremos nuestros testsss
      - name: Run unit tests
        run: |
          pytest

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "146.59.155.170"
          username: ${{ secrets.HOSTNAME }}
          password: ${{ secrets.HOSTPASS }}
          port: 22
          source: "docker/docker-compose.yml"
          target: "prueba"
          
      - name: Deploy to Staging
        uses: JorgenVatle/docker-compose-deploy@v1.0
        with:
         deploy_targets: "146.59.155.170" # required, comma separated list of servers to deploy to.
         ssh_user: ${{ secrets.HOSTNAME }} # optional, user to connect to deploy targets with. Defaults to 'root'
         compose_file: "docker/docker-compose.yml" # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
         validate_container: 'app' # optional, validate that the given container name is running. Otherwise, throw an error. Defaults to 'app'       
