name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 
      - uses: actions/checkout@v2

      # Vamos a establecer un environment de python 3.6
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
        
                
      # Instalamos la dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Corremos nuestros testsss
      - name: Run unit tests
        run: |
          pytest

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "146.59.155.170"
          username: ${{ secrets.HOSTNAME }}
          password: ${{ secrets.HOSTPASS }}
          port: 22
          source: "./docker-compose.yml, ./docker-entrypoint.sh, ./Dockerfile"
          target: "."
          
      - name: Docker Compose Actions Workflow       
        uses: actions/checkout@v2
            
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag dafecueto/rockpaperscissors:latest
      - name: Push the latest Docker image
        run: docker push dafecueto/rockpaperscissors
